### PR TITLE
#71 瓦片图切图工具依赖库

### PR DESCRIPTION
**Pull request by fdddf**
#71 提交代码

### CODE REVIEW

**Comment by fdddf** [comment]
[template_qa_局部模板_瓦片图工具依赖库_1.0.0.zip](https://github.com/netease-lcap/CodeWaveAssetCompetition2024/files/15310640/template_qa_._._1.0.0.zip)

**Comment by fdddf** [comment]
[template_qa_局部模板_瓦片图工具依赖库_1.0.1.zip](https://github.com/netease-lcap/CodeWaveAssetCompetition2024/files/15353930/template_qa_._._1.0.1.zip)

**Comment by JiazhenBao** [comment]
功能审核中

**Comment by fdddf** [comment]
[template_qa_局部模板_瓦片图工具依赖库_1.0.2.zip](https://github.com/netease-lcap/CodeWaveAssetCompetition2024/files/15391933/template_qa_._._1.0.2.zip)

**Pull request merged**
